APPLY_FIXES: none
FILTER_REGEX_EXCLUDE: (karma.config.js|polyfill.js)
VALIDATE_ALL_CODEBASE: true
REPOSITORY_DEVSKIM_DISABLE_ERRORS: true

DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - C_CPPLINT
  - CPP_CPPLINT
  - BASH_SHELLCHECK
  - BASH_EXEC
