branches:
  - name: "main"
  - name: "release/*"
    prerelease: "snapshot"

plugins:
  # - "@semantic-release/commit-analyzer"
  # - "@semantic-release/release-notes-generator"
  # - ["@semantic-release/changelog", {changelogFile: "CHANGELOG.md"}]
  # - "gradle-semantic-release-plugin"
  # - [ '@semantic-release/exec', {
  #   prepareCmd: './gradlew :apollo:createSwiftPackage' } ]
  # - [ '@semantic-release/exec', {
  #   prepareCmd: '(cd ./apollo/build/packages/ApolloSwift && zip -r "Apollo.xcframework.zip" Apollo.xcframework)' } ]
  - [ '@semantic-release/exec', {
      prepareCmd: 'CHECKSUM=`swift package compute-checksum ./apollo/build/packages/ApolloSwift/Apollo.xcframework.zip` sed -i.bak -e "s/checksum:.*/checksum: \"${CHECKSUM}\"/g;s/download\/.*\/Apollo.xcframework.zip/download\/${nextRelease.version}\/Apollo.xcframework.zip/g" Package.swift'
    }
    ]
  # - [
  #   "@semantic-release/git",
  #   {
  #     assets: [
  #       "CHANGELOG.md",
  #       "gradle.properties",
  #     ],
  #     message: "chore(release): cut apollo version ${nextRelease.version}

  #       ${nextRelease.notes}",
  #   },
  # ]
  # - [
  #   "@semantic-release/github",
  #   {
  #     "assets": [
  #       { "path": "apollo/build/packages/ApolloSwift/Apollo.xcframework.zip", "label": "Apollo.xcframework.zip" },
  #     ]
  #   }
  # ]
  # - [
  #   "semantic-release-slack-bot",
  #   {
  #     notifyOnSuccess: true,
  #     notifyOnFail: true,
  #     markdownReleaseNotes: true,
  #     onSuccessTemplate:
  #       {
  #         text: "A new version of `$package_name` successfully released!\n
  #           Version: `v$npm_package_version`\n
  #           Tag: $repo_url/releases/tag/v$npm_package_version\n
  #           \n
  #           Release notes:\n
  #           $release_notes"
  #       },
  #   },
  # ]
